export const SERVICES = {
  drivers: {
    key: 'drivers',
    label: 'Drivers',
    icon: '🚗',
    color: '#F59E0B',
    description: 'Hire experienced, verified drivers for local rides, outstation trips, or airport transfers.',
    providerLabel: 'Driver',
    apiBase: '/api/drivers',
    profileFields: ['vehicle_type', 'license_number', 'languages'],
    filterFields: [
      { name: 'city', label: 'City', type: 'text' },
    ],
    bookingFields: [
      { name: 'trip_type', label: 'Trip Type', type: 'select', options: ['hourly', 'outstation', 'airport', 'local_commute'], required: true },
      { name: 'vehicle_by', label: 'Vehicle Provided By', type: 'select', options: ['consumer', 'driver'], required: true },
      { name: 'duration_hours', label: 'Duration (hours)', type: 'number', min: 1, required: true },
      { name: 'address', label: 'Pickup Address', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text', required: true },
      { name: 'scheduled_at', label: 'Scheduled Date & Time', type: 'datetime-local', required: true },
      { name: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  barbers: {
    key: 'barbers',
    label: 'Barbers',
    icon: '✂️',
    color: '#10B981',
    description: 'Professional barbers at your doorstep — haircuts, beard grooming, and more.',
    providerLabel: 'Barber',
    apiBase: '/api/barbers',
    profileFields: ['specializations', 'service_radius_km'],
    filterFields: [
      { name: 'city', label: 'City', type: 'text' },
    ],
    bookingFields: [
      { name: 'requested_services', label: 'Services Required', type: 'text', placeholder: 'Haircut, Beard Trim, Shave…', required: true },
      { name: 'duration_estimate', label: 'Estimated Duration (mins)', type: 'number', min: 15, required: true },
      { name: 'address', label: 'Address', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text', required: true },
      { name: 'scheduled_at', label: 'Scheduled Date & Time', type: 'datetime-local', required: true },
      { name: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  carpenters: {
    key: 'carpenters',
    label: 'Carpenters',
    icon: '🪚',
    color: '#8B5CF6',
    description: 'Skilled carpenters for furniture repair, installation, custom builds, and assembly.',
    providerLabel: 'Carpenter',
    apiBase: '/api/carpenters',
    profileFields: ['wood_specialization', 'has_own_tools'],
    filterFields: [
      { name: 'city', label: 'City', type: 'text' },
    ],
    bookingFields: [
      { name: 'work_type', label: 'Work Type', type: 'select', options: ['repair', 'installation', 'custom_work', 'assembly', 'inspection'], required: true },
      { name: 'materials_by', label: 'Materials Provided By', type: 'select', options: ['consumer', 'carpenter', 'discuss'], required: true },
      { name: 'estimated_duration_hrs', label: 'Estimated Duration (hrs)', type: 'number', min: 1, required: true },
      { name: 'address', label: 'Address', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text', required: true },
      { name: 'scheduled_at', label: 'Scheduled Date & Time', type: 'datetime-local', required: true },
      { name: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  electricians: {
    key: 'electricians',
    label: 'Electricians',
    icon: '⚡',
    color: '#EF4444',
    description: 'Licensed electricians for wiring, repairs, panel upgrades, and emergency services.',
    providerLabel: 'Electrician',
    apiBase: '/api/electricians',
    profileFields: ['license_number', 'available_emergency'],
    filterFields: [
      { name: 'city', label: 'City', type: 'text' },
      { name: 'emergency', label: 'Emergency Only', type: 'checkbox' },
    ],
    bookingFields: [
      { name: 'work_type', label: 'Work Type', type: 'select', options: ['repair', 'wiring', 'installation', 'panel_upgrade', 'inspection'], required: true },
      { name: 'priority', label: 'Priority', type: 'select', options: ['normal', 'urgent', 'emergency'], required: true },
      { name: 'estimated_duration_hrs', label: 'Estimated Duration (hrs)', type: 'number', min: 1, required: true },
      { name: 'address', label: 'Address', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text', required: true },
      { name: 'scheduled_at', label: 'Scheduled Date & Time', type: 'datetime-local', required: true },
      { name: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  lawyers: {
    key: 'lawyers',
    label: 'Lawyers',
    icon: '⚖️',
    color: '#3B82F6',
    description: 'Consult verified lawyers for property, family, labour, business, and criminal matters.',
    providerLabel: 'Lawyer',
    apiBase: '/api/lawyers',
    profileFields: ['bar_registration', 'practice_areas', 'languages'],
    filterFields: [
      { name: 'city', label: 'City', type: 'text' },
    ],
    bookingFields: [
      { name: 'legal_area', label: 'Legal Area', type: 'select', options: ['property', 'family', 'labour', 'criminal', 'business', 'civil', 'other'], required: true },
      { name: 'consultation_type', label: 'Consultation Type', type: 'select', options: ['initial', 'follow_up', 'document_review', 'contract_review'], required: true },
      { name: 'duration_minutes', label: 'Duration', type: 'select', options: [30, 60, 90], required: true },
      { name: 'address', label: 'Location / Address', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text', required: true },
      { name: 'scheduled_at', label: 'Scheduled Date & Time', type: 'datetime-local', required: true },
      { name: 'notes', label: 'Case Notes / Context', type: 'textarea' },
    ],
  },
  labourers: {
    key: 'labourers',
    label: 'Labourers',
    icon: '🏗️',
    color: '#F97316',
    description: 'Dependable daily wage workers for moving, cleaning, construction, and more.',
    providerLabel: 'Labourer',
    apiBase: '/api/labourers',
    profileFields: ['skills', 'daily_rate'],
    filterFields: [
      { name: 'city', label: 'City', type: 'text' },
      { name: 'skill', label: 'Skill', type: 'text' },
    ],
    bookingFields: [
      { name: 'work_type', label: 'Work Type', type: 'select', options: ['moving', 'cleaning', 'construction', 'loading', 'gardening', 'other'], required: true },
      { name: 'num_workers', label: 'Number of Workers', type: 'number', min: 1, required: true },
      { name: 'work_days', label: 'Number of Days', type: 'number', min: 1, required: true },
      { name: 'address', label: 'Work Address', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text', required: true },
      { name: 'scheduled_at', label: 'Start Date', type: 'datetime-local', required: true },
      { name: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
};

export const SERVICE_LIST = Object.values(SERVICES);
